# Generated by Django 3.2.12 on 2022-04-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hide_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
