# Generated by Django 3.2.12 on 2022-03-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladder',
            old_name='file',
            new_name='fileup',
        ),
    ]
