# Generated by Django 3.2.12 on 2022-03-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0002_rename_file_ladder_fileup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladder',
            old_name='fileup',
            new_name='file',
        ),
    ]
