# Generated by Django 3.2.12 on 2022-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0003_rename_fileup_ladder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='content_type',
            field=models.TextField(default='image/jpeg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ladder',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
