# Generated by Django 3.2.12 on 2022-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0004_auto_20220314_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
