# Generated by Django 3.2.12 on 2022-03-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0005_ladder_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='user_name',
            field=models.TextField(default='lakhi'),
            preserve_default=False,
        ),
    ]
