# Generated by Django 3.2.12 on 2022-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0008_ladder_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
    ]
